"""Mejoras en productos (paginación, filtros, imágenes)

Revision ID: 1a5099b9e836
Revises: ec32ea98e829
Create Date: 2025-02-15 22:36:01.829192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a5099b9e836'
down_revision: Union[str, None] = 'ec32ea98e829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comparison_products_product_id_fkey', 'comparison_products', type_='foreignkey')
    op.drop_constraint('comparison_products_comparison_id_fkey', 'comparison_products', type_='foreignkey')
    op.create_foreign_key(None, 'comparison_products', 'comparisons', ['comparison_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comparison_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_user_comparison_title', 'comparisons', ['user_id', 'title'])
    op.drop_constraint('comparisons_user_id_fkey', 'comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'comparisons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'published_at')
    op.drop_column('products', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.create_foreign_key('comparisons_user_id_fkey', 'comparisons', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_comparison_title', 'comparisons', type_='unique')
    op.drop_constraint(None, 'comparison_products', type_='foreignkey')
    op.drop_constraint(None, 'comparison_products', type_='foreignkey')
    op.create_foreign_key('comparison_products_comparison_id_fkey', 'comparison_products', 'comparisons', ['comparison_id'], ['id'])
    op.create_foreign_key('comparison_products_product_id_fkey', 'comparison_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
