"""Agregando campo role a UserResponse

Revision ID: 1f825b3a3930
Revises: e7dc7ff2d8f0
Create Date: 2025-02-17 18:28:02.249489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f825b3a3930'
down_revision: Union[str, None] = 'e7dc7ff2d8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
