"""Agregando campo role a UserResponse

Revision ID: 669933c9c453
Revises: 1f825b3a3930
Create Date: 2025-02-17 18:31:43.345176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669933c9c453'
down_revision: Union[str, None] = '1f825b3a3930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
