"""Actualización de esquemas

Revision ID: 802b7cfcb2e5
Revises: 669933c9c453
Create Date: 2025-02-18 16:24:34.448888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802b7cfcb2e5'
down_revision: Union[str, None] = '669933c9c453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
