"""Agregando campo role a UserResponse

Revision ID: e7dc7ff2d8f0
Revises: eca7fae37821
Create Date: 2025-02-17 18:27:37.210056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dc7ff2d8f0'
down_revision: Union[str, None] = 'eca7fae37821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
