"""Updated schema with Cloudinary support

Revision ID: ec32ea98e829
Revises: 8dd4bb6b00c5
Create Date: 2025-02-15 12:54:57.915364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec32ea98e829'
down_revision: Union[str, None] = '8dd4bb6b00c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('products', 'sections')
    op.drop_column('products', 'images')
    op.drop_column('products', 'attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
