"""Agregando campo role a UserResponse

Revision ID: eca7fae37821
Revises: 3840ce15f0a5
Create Date: 2025-02-17 17:32:16.418820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca7fae37821'
down_revision: Union[str, None] = '3840ce15f0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
