"""Actualización de esquemas

Revision ID: fc6386e67d3b
Revises: 802b7cfcb2e5
Create Date: 2025-02-18 16:31:27.228111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6386e67d3b'
down_revision: Union[str, None] = '802b7cfcb2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
